### ISSUE TITLE
Amazing!  minor problem when behind transparent activity

### ISSUE THREAD

**Issue by smhk** [sergei-lapin/BlurView#1]
1. Library is INCREDIBLE

2. I put a full screen BlurView on my activity

3. It works perfectly

4. I launch a new activity on top (side menu) with windowBackground transparent

5. Unfortunately, the BlurView just goes all-black.

Could there be a quick fix ?

Thanks!  amazing library

**Comment by smhk** [comment]
It's a RECENT ANDROID BUG:

https://stackoverflow.com/a/67045156/294884

no problem with this amazing library!  **AMAZING LIBRARY !!**

**Comment by sergei-lapin** [comment]
Thanks for the feedback, closing the issue though
