### ISSUE TITLE
Possibly does not blur TextViews

### ISSUE THREAD

**Issue by smhk** [sergei-lapin/BlurView#2]
Amazing library thanks.

I am blurring the full screen.  (For typical use, a "left menu" with blur of activity behind.)

FYI.  It is possible that TextViews are not blurred.

**Comment by sergei-lapin** [comment]
Could you provide an example (maybe a screenshot)? 
There's actually no differentiation between what is blurred since all underlying content is captured as bitmap

**Comment by smhk** [comment]
For sure!  I am trying to identify what sort of text is not-blurred.  Some blurs, some does not.

This on a samsung A51

![a](https://user-images.githubusercontent.com/3938526/114418932-99952000-9b78-11eb-91b8-abbaf070cca3.png)

![b](https://user-images.githubusercontent.com/3938526/114419026-ae71b380-9b78-11eb-99ec-087e1abaeaae.png)

(Purple area is a menu activity in front; it makes no difference at all if another activity is in front.)

Thanks - amazing lib.

**Comment by smhk** [comment]
Note that "Blurry" for instance has never been able to blur text.  So it will be a nice win if BlurView can do it !  :)

**Comment by sergei-lapin** [comment]
Hi, BlurView does blur texts, you've only got to layer it correctly. 
Here's an example.
![image](https://user-images.githubusercontent.com/20017521/115113035-ab742a00-9fa1-11eb-8b0b-968f08dbdf5f.png)
Please refer to the [updated sample's layout](https://github.com/sergei-lapin/BlurView/blob/main/sample/src/main/res/layout/activity_main.xml) for more info. 

Closing this
